### PR TITLE
Home UI Improvement - Card, Heading, Nav Hover 

### PR DESCRIPTION
**Pull request by ojasaklechayt**
## Related Issue

Improved Home page UI

Closes: #442 

### Describe the changes you've made

Changes -
1. Navbar hover color change
2. Heading color improvement
3. Card ui improvement

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

Added before and after screenshots

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
Before:
| image | image |

| image | image |

| image | image |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by thehashmap — COMMENTED** [review]
The changes look fine, but I like the current card UI more.

Other design changes are good

**Review by Anmol-Baranwal — COMMENTED** [review]
Apart from the main landing page headline, I don't believe that the other designs have a significant impact or bring about significant changes in the user experience.

image

> Everything functions as intended, so I am approving the pull request.

**Comment by ojasaklechayt** [comment]
> The changes look fine, but I like the current card UI more.
> 
> Other design changes are good

changed to previous one

**Comment by Anmol-Baranwal** [comment]
Hi @ojasaklechayt 

I didn't request you to make any changes because if I had, I would have mentioned them specifically. Please allow others to review the code, and based on their feedback, you will have a better understanding. Therefore, refrain from making any additional changes at this time.

image

**Review by vinzvinci — COMMENTED** [review]
The current one is fine for me

**Review by vinzvinci — COMMENTED** [review]
Thanks for your time and contributions. We agreed to not work on this for now since the current version is fine than this pr.

**Pull request closed without merging**
