### PR TITLE
bug: updated twitter icon new x icon

### PR DESCRIPTION
**Pull request by SudeeptaGiri**
## Related Issue

- As Twitter logo is changed we need to change twitter logo now in our website 

Closes: #525

### Describe the changes you've made

changed the Old Twitter Logo to new  X Logo
I just added the SVG path of X 
It is working fine for both Dark mode and Light Mode

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run the code in My System in the Microsoft Edge Browser and in the FireFox Browser too and it is working fine

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
|  Screenshot 2023-10-24 110930 | Screenshot 2023-10-24 110910 |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by s2sharpit — APPROVED** [review]
LGTM!, Congrats on your first commit @SudeeptaGiri.

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Comment by s2sharpit** [comment]
It looks great to me. I'm merging this PR.

**Comment by SudeeptaGiri** [comment]
Thank You @s2sharpit  :-)

**Pull request merged**
