### PR TITLE
adding gap between navbar and main content

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue

Closes: #408  

### Describe the changes you've made
Added margin bottom on site header

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev @Panquesito7
Please check this PR.

**Review by mkubdev — COMMENTED** [review]
Hello!
Sorry but this one is invalid, it break the hero: 
image

#408 problem isn't due to gap, but due to the size of the image in the hero in small screen size. We should instead reduce the size of the cube on the hero component with tailwind breakpoint maybe... :)

**Comment by s2sharpit** [comment]
Hey @mkubdev 
I'm sorry for that.
I have fixed the error. Please check it again.
Thankyou

**Review by Anmol-Baranwal — COMMENTED** [review]
I have very good experience in user interface design with emphasis on user experience.

Currently, there is very little gap between the hero illustration and the navbar. However, since the illustration is just for visual appeal and the main content is placed in between, it is my opinion that adding padding may not be necessary as it wouldn't significantly impact the visual hierarchy.
However, it ultimately depends on the overall design and aesthetic preferences.

The change works as mentioned :)

**Comment by Anmol-Baranwal** [comment]
@vinzvinci 
I have already reviewed the PR.

**Review by Mustafiz04 — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]

**Review by mkubdev — APPROVED** [review]
I share @Anmol-Baranwal pov, but lgtm!

**Pull request merged**
