### PR TITLE
Made hover changes in scroll to top button

### PR DESCRIPTION
**Pull request by Riyazul555**
## Related Issue

- Information about the related issue

Closes: #456 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Riyazul555** [comment]
The current hovering effect matches the theme of the project in both light and dark mode 

Screenshot (325)
Screenshot (326)

**Comment by Riyazul555** [comment]
@Anmol-Baranwal please review this pR .........Thanks

**Comment by Anmol-Baranwal** [comment]
@Riyazul555 

Please follow the instructions mentioned in the pr comment.

> Image
image

I am providing this feedback because you appear to be a first-time contributor.

It is helpful to include links to issues so that we can understand which issue you are working on and ensure it is properly linked here.

I have done it for you, but please make sure to fill in the descriptions accurately, as otherwise, your pull request may not be reviewed by anyone.

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
@Riyazul555 
You have added the wrong code, which caused the deployment to fail. Make sure to run it properly locally so that it functions the same way when Vercel deploys the PR. 

> Remove any unnecessary code, except for the CSS files.

image

**Pull request closed without merging**
