### PR TITLE
ADD: FOOTER SECTION FOR V3 REBRANDING WEBSITE

### PR DESCRIPTION
**Pull request by MAYANKpandey14**
## Creation of Footer section for the v3 rebranding website.

Closes: #289 

### Describe the changes you've made
Create a footer section 
Add new links required for the footer section
Update next.config file to debug run-time error due to next/image.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
Google Chrome DevTools

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

Screenshot from 2023-05-22 00-02-26 
Screenshot from 2023-05-22 00-06-15 
Screenshot from 2023-05-22 00-06-49

 ### Runtime Error causing inability to start development server
Screenshot from 2023-05-23 12-27-46

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by MAYANKpandey14** [comment]
I have no idea why this error is coming up after starting server using npm run dev command.
Screenshot from 2023-05-23 13-08-19

My terminal shows this 
Screenshot from 2023-05-23 13-10-04

I think this createPropError function is the reason behind this error 

Screenshot from 2023-05-23 13-11-29

**Comment by darkterminal** [comment]
Did you have to check ghe `Link` value?

**Comment by darkterminal** [comment]
You're pushed in `v3` branch. Did you try pull our latest changes from `main` branch? and try to push your latest work in the `main` branch.

**Review by darkterminal — CHANGES_REQUESTED** [review]
What you need is, to try to change social links in `site-header.tsx` and everything is working like :rocket:

**Comment by MAYANKpandey14** [comment]
> You're pushed in `v3` branch. Did you try pull our latest changes from `main` branch? and try to push your latest work in the `main`

**Comment by MAYANKpandey14** [comment]
> What you need is, to try to change social links in `site-header.tsx` and everything is working like rocket

Thanks, it works completely fine now.

**Comment by darkterminal** [comment]
Woooo... the :rocket: is launched now!!!!

**Review by vinzvinci — COMMENTED** [review]
Awesome! Adding label now!

**Comment by MAYANKpandey14** [comment]
> Awesome! Adding label now!

Thanks very happy to contribute. More PRs incoming  Godspeed ⚡

**Comment by darkterminal** [comment]
@vinzvinci The Judge! :hammer: :rofl:

**Comment by vinzvinci** [comment]
> @vinzvinci The Judge! 🔨 🤣

LMAO 😆

**Pull request merged**
