### PR TITLE
fix: z-index issue for card overlay on hover

### PR DESCRIPTION
**Pull request by parthpathakpp1**
## Related Issue

Previously Cards were going on top while hovering . Now it is fixed . 

Closes: #383 

### Describe the changes you've made
Now Community Partners cards does not go on top of the navbar . 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| 

https://github.com/WebXDAO/WebXDAO.github.io/assets/85991449/3579d83d-1f76-4a44-a776-f4e8fd3babd7

 |

https://github.com/WebXDAO/WebXDAO.github.io/assets/85991449/5af847de-9f21-4aff-b9f7-e49fb4f71b48

 |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by parthpathakpp1** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev @Panquesito7
Please check this PR.

**Review by Anmol-Baranwal — APPROVED** [review]
Works as mentioned :)

**Comment by parthpathakpp1** [comment]
Can you please give label .

**Comment by Anmol-Baranwal** [comment]
@vinzvinci 
I have attached a label of Level1 PR. Please review and make any necessary changes.

**Comment by vinzvinci** [comment]
Thanks @Anmol-Baranwal, all good!

**Pull request merged**
