### PR TITLE
feat: Add/moderators

### PR DESCRIPTION
**Pull request by shreyaansjain06**
## Related Issue 

- Information about the related issue 

Closes: #91  

### Describe the changes you've made
Made a page for moderators

## Type of change
Added new page

What sort of change have you made:
Added new moderators folders and moderators.html file with some css

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
On my local host

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
Screenshot 2021-10-17 at 11 29 18 PM | Screenshot 2021-10-17 at 11 29 51 PM |
 
## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by shreyaansjain06** [comment]
Sorry for the typo

**Comment by shreyaansjain06** [comment]
Added social handles any more suggestions

Screenshot 2021-10-18 at 11 26 41 AM

**Comment by krishguptadev** [comment]
> Added social handles any more suggestions
> 
> Screenshot 2021-10-18 at 11 26 41 AM

Whitespace issues. Add a bit more padding and margin inside of the card

**Comment by shuklaritvik06** [comment]
SS
I think this looks good @shreyaansjain06  What you say?

**Pull request merged**
