### PR TITLE
fixing Partners Card z-index on hover

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue
Card on hover increase in size and render over the navbar decreasing it effectiveness

Closes: #395 

### Describe the changes you've made
Fixed the z-index on hover

Remove z-index from Partners Card on hover and increased z-index of navbar

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev @Panquesito7 
Please check this PR.

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🚀

**Review by vinzvinci — COMMENTED** [review]
Thanks for contributions! 

Already mentioned gssoc mentors and developers guild to review this PR but wait them this coming weekdays.

**Review by Anmol-Baranwal — APPROVED** [review]
Works as mentioned :)

**Comment by Anmol-Baranwal** [comment]
@vinzvinci 
This PR is identical to #410

**Comment by s2sharpit** [comment]
As issue #383, which prompted the creation of pull request #410, was actually raised prior to #395. Therefore, I would like to close this pull request, as the task should be addressed and completed by #383.

**Comment by Anmol-Baranwal** [comment]
> As issue #383, which prompted the creation of pull request #410, was actually raised prior to #395. Therefore, I would like to close this pull request, as the task should be addressed and completed by #383.

Let's wait for the decision of @vinzvinci

**Comment by vinzvinci** [comment]
Thanks a lot for your contributions, let's close this one and move forward!

**Pull request closed without merging**
