### PR TITLE
chore: add `autoprettier` github action

### PR DESCRIPTION
**Pull request by mkubdev**
## Related Issue

- Information about the related issue

Closes: #221 

### Describe the changes you've made

* Setup `autoprettier.yaml` GitHub Action to autoformat files
* Formated the projects
* Added prettier.rc with double quote format config
* Fixed the `Navbar` component which used vanilla router -> replaced by nextjs `Link` router
* Removed multiples circles absolute div: not matching our current design
* Removed a `grid` class which breaked the `contributor` and `blog` page (there was already a `flex` + `flex wrap` so no need of using `grid` here!)

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/223"></a>

### CODE REVIEW

**Review by krshkun — CHANGES_REQUESTED** [review]
Pretittier really confilcts with eslint and eslint with a code style configurations works better than prettier and also tells the errors and warnings instead of just saying that "you forgot to run prettier"

Therefore I do not recommend prettier

**Comment by krshkun** [comment]
> Not to mention, that 2 days ago, you were [ok for it! (Prettier)](https://github.com/WebXDAO/WebXDAO.github.io/pull/212#issuecomment-1264539977)

Not to mention, that 2 days ago, you were https://github.com/WebXDAO/WebXDAO.github.io/pull/212#issuecomment-1264539977

I do not mean to have the kind of prettier config you are talking about - just one that is going to use the ESLint config - I think prettier have plugin for that

**Comment by mkubdev** [comment]
@krshkun Oki! What if we open a new issue for replacing the prettier thing? I think that'll be proper tasks to see how eslint replace prettier from this new issue!

**Review by krshkun — APPROVED** [review]
In that case, let's merge this but heads up Codacy is going to fail on basically on all PRs so we'll have to ignore it /cc @vinzvinci @Panquesito7 @shuklaritvik06 (Tagging the maintainers) 👍

**Review by shuklaritvik06 — APPROVED** [review]

**Pull request merged**
