### PR TITLE
Used new Discord invitation link

### PR DESCRIPTION
**Pull request by karthickbharathi1**
## Related Issue

- Information about the related issue

Closes: # 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by karthickbharathi1** [comment]
Hi @Panquesito7 . I have fixed the issue abd used the new discord link.

**Review by shuklaritvik06 — APPROVED** [review]

**Comment by shuklaritvik06** [comment]
> Hi @Panquesito7 . I have fixed the issue abd used the new discord link.

Hey 👋🏼  Thanks for the PR but you should always first comment on the issue to get it assigned to you and then work on it, it would avoid confusion for other folks :) For now I am merging this

**Comment by karthickbharathi1** [comment]
Sorry @shuklaritvik06. I will make sure to first get assigned and then work on it. Thanks for merging!!

**Review by Panquesito7 — COMMENTED** [review]
Looks good! Thanks for contributing. 🎉

**Pull request merged**
