### PR TITLE
[ADDED]: sitemap.xml

### PR DESCRIPTION
**Pull request by Killer2OP**
## Related Issue

A sitemap is a file that lists all the pages of a website, helping search engines understand its structure and content.

Closes: #468 

### Describe the changes you've made

Added the sitemap.xml in public folder

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Killer2OP** [comment]
@Anmol-Baranwal Can you please review the PR.

**Review by Panquesito7 — APPROVED** [review]
Looks good. Thansk! 🚀

**Review by Anmol-Baranwal — COMMENTED** [review]
@vinzvinci 
Don't you think, `https://webxdao.xyz/` should have a higher priority than others?

Everything looks good to me.

**Comment by vinzvinci** [comment]
> @vinzvinci Don't you think, `https://webxdao.xyz/` should have a higher priority than others?
> 
> Everything looks good to me.

Yes for now

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Comment by Anmol-Baranwal** [comment]
> > @vinzvinci Don't you think, `https://webxdao.xyz/` should have a higher priority than others?
> > Everything looks good to me.
> 
> Yes for now

Then there should be changes in the code for the higher relative priority of homepage

**Comment by Killer2OP** [comment]
@Anmol-Baranwal  Can you add the appropriate label to the PR.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal Can you add the appropriate label to the PR.

Thanks for notifying us. Don't worry about the level of the PR, I will change if needed.

**Pull request merged**
