### PR TITLE
Made hover effects in top scroll button

### PR DESCRIPTION
**Pull request by Riyazul555**
## Related Issue

- Information about the related issue

Closes: #456 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Riyazul555** [comment]
Screenshot (329)
Screenshot (330)

**Comment by Riyazul555** [comment]
@Anmol-Baranwal I made a new pR as you told me and it passed all the checks .........I made the changes for the top button effects to make it more illustrative according to issue #456.........For some reasons I am unable to link the issue .......Please review  it ......Thanks

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
`There are few problems with this pull request.`

Also, please refrain from making new PRs.

1. Why is there a change in package-lock.json at so many locations

> Image
image

2. There are absolutely no change, add significant changes to make it worth merging the PR. Also, the color doesn't even match, pick the color from logo or heading based on accessibility.

> No hover
image

> Hover
image

> My suggestion
image

**Comment by Riyazul555** [comment]
@Anmol-Baranwal the changes in package-lock.json are done when I installed npm packages and that happened automatically

**Comment by Riyazul555** [comment]
Ok @Anmol-Baranwal ...take your time and check it and let me know .......Thanks

**Comment by Anmol-Baranwal** [comment]
> Ok @Anmol-Baranwal ...take your time and check it and let me know .......Thanks

Which command did you use for the same.

**Comment by Riyazul555** [comment]
@Anmol-Baranwal I used npm install as mentioned in your contributing guidelines

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal I used npm install as mentioned in your contributing guidelines 

Can you provide commands that you used in this particular branch.

**Review by vinzvinci — COMMENTED** [review]
Any update on this?

**Comment by Riyazul555** [comment]
@vinzvinci give me some time...... little busy with my exams 😅

**Review by vinzvinci — COMMENTED** [review]
Hi, just want to update that the GSSOC is nearly done.

**Pull request closed without merging**
