### PR TITLE
Solved Issue #341 [FEATURE] Create Updated Navbar based on V3 design files [GSSoC'23]

### PR DESCRIPTION
**Pull request by vishnu9865**
## Related Issue

 - Change the Navbar with Updated design according to the V3 rebranding [Figma file](https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=0-1&t=ksleMxOBsRQ7u0pd-0).
 - But also include the Theme toggler and links from the old design.
 -  And also the Footer section if possible.

Closes: #341 

### Describe the changes you've made
[feat] Redesign navbar to v3 design
 - Moved Github, Twitter, and Theme Toggler inside main-nav component and grouped them into a div (icon links).
 - grouped navigation links into div.
 - Changed the gaps and space between the divs for realignment.
 - Realigned Hamburger menu to right.
 - Added V3 design logo to public folder and to the website.
 - The new logo is compatible with both dark and light themes.

## Type of change

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
Chrome DevTools in Responsive Mode.

## Checklist

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| image | image |
| Original (md size) | Updated (md size) |
| image (bug)| image |
| Original (sm size) | Updated (sm size) |
| image | image |
| Original Menu | Updated Menu |
| image | image |
| Logo on light mode | Logo on dark mode |
| image | image |

## Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by vinzvinci — COMMENTED** [review]
Thank you! 

Please wait our team. It's weekend, so it may take time for them to review this PR!

**Comment by vishnu9865** [comment]
@vinzvinci Sir,
It's okay sir I understand 👍👍😊 Glad to be part of WebXDAO community.

**Review by mkubdev — APPROVED** [review]
Hello :wave: ! This look good to me, you did a great work on the navbar! :) ⚡
Thanks a lot for your contribution. I added you `level 2` badge for your implication and code quality! Well done again.

**Comment by vishnu9865** [comment]
@mkubdev Thank you sir,
 - This means a lot to me.
 - I hope to learn a lot more from contributing to this project and from you guys.
 - very grateful for this experience. 😊😊👍🏽🔥.

**Pull request merged**
