### PR TITLE
Solved Issue #323 [FEATURE] Add Contributors Page [GSSOC'23]

### PR DESCRIPTION
**Pull request by vishnu9865**
## Related Issue

- Add Separate Contributors Page
- Page expected to be visually similar to the given [Figma File](https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=0-1&t=ksleMxOBsRQ7u0pd-0)

Closes: #323 

#### listed in order of Files added or modified*
 - **contributors/page.tsx (addition)**
   - Created a page.tsx file (nextjs 13).
   - An async function fetches contributor list using Github API
   - Maps the JSON data to individual 'contributor components'.
 - **components/ContributorCard.tsx (addition)**
   - returns a Individual Contributor Card Component.
   - Takes username, no of contributions and url as props
 - **lib/font.ts (modification)**
   - A new local font Gilroy according to the given Figma design was added as exportable constant using 'next/font/local'
 - **public/fonts/gilroy (addition)**
   - Font folder containing Gilroy fonts for the page.
 - **public/hand-shake.svg (addition)**
   - hand-shake icon given in Figma design of the page was added as a public asset for use.
 
## Key Takeaways:
Features other than Visual similarity.
 - The Contributor list is loaded **dynamically** using GitHub REST API.
 - All contributor page components are **Server Rendered**.
 - Every contributor card component is clickable **Links** to their profile url.
 - The contributor card component is optimized for both **DARK/LIGHT modes**.
 - The only missing things in the contributors page on comparison to figma file are the older Navbar and no footer.
 - For implementing the navbar and footer (if possible) from the figma design, I have created Issue #341 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

 - Changes were verified through responsive changes in browser window.
 - Github API Data fetch was verified to be unchanged.
 - Visual UI/UX similarity was verified with figma design.

## Checklist

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| image | image |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Comment by darkterminal** [comment]
Can you give any related description on these pages and make every card have its avatar, name, and contribution count, and make I think we can make it clickable to that card and redirect to their profile or in our repository contribution graph (:thinking:) @vinzvinci

**Comment by vinzvinci** [comment]
I didn't notice the issues sorry. The contributor page design is not done as designers team said @darkterminal.

**Comment by darkterminal** [comment]
Oh yeah... that's gwrrreat example!
But I think this suggestion is worth trying and implementing while waiting for confirmation from our designers. How bout that @vinzvinci

**Comment by vinzvinci** [comment]
> Oh yeah... that's gwrrreat example! But I think this suggestion is worth trying and implementing while waiting for confirmation from our designers. How bout that @vinzvinci

Yeah, we can make changes once the design is done for this page.

**Comment by vishnu9865** [comment]
> I didn't notice the issues sorry. The contributor page design is not done as designers team said @darkterminal.
> 
> We need to put something like this https://tailwindui.com/components/marketing/sections/team-sections#component-d3acbf5cf2bb7ba7f94bbe6e0b30ed2f

@darkterminal @vinzvinci ,
 -  I would be happy to help you guys with this vision of the website rebranding. ❤️
 - The Figma Designs already look amazing
 - I made the Contributor cards clickable already so only a few changes are required.

Always happy to help
Regards,
Jeyavishnu @vishnu9865

**Comment by Mustafiz04** [comment]
> Can you give any related description on these pages and make every card have its avatar, name, and contribution count, and make I think we can make it clickable to that card and redirect to their profile or in our repository contribution graph (🤔) @vinzvinci @WebXDAO/webx-guild @WebXDAO/webx-guild-developer

Yeah, I can feel the same, we can do something more interesting with this page.

**Comment by vishnu9865** [comment]
@vinzvinci sir,
Sorry, 😅 Simple file path correction.
image

**Review by vinzvinci — APPROVED** [review]
This is awesome!!!!! LGTM ✅ 

For the future changes to design, feel free to raise an issue and we can assign it to you.

**Comment by vishnu9865** [comment]
@vinzvinci 
I looking forward to it.
Until then I am working on updated design navbar #341

**Comment by shuklaritvik06** [comment]
> I didn't notice the issues sorry. The contributor page design is not done as designers team said @darkterminal.
> 
> We need to put something like this https://tailwindui.com/components/marketing/sections/team-sections#component-d3acbf5cf2bb7ba7f94bbe6e0b30ed2f

Awesome idea!

**Comment by darkterminal** [comment]
:rocket: just 🔥

**Comment by darkterminal** [comment]
calling @vinzvinci

**Pull request merged**
