### PR TITLE
Updating Blog page

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue

Closes: #305 

### Describe the changes you've made
Updating Blog Page.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by s2sharpit** [comment]
Subject: Assistance Needed to Complete Blog Page

Hey @Anmol-Baranwal and @vinzvinci,

I hope this message finds you both well. I wanted to reach out and let you know that I have successfully added as much data as I could for the cards on the blog page. However, there is still some missing information that requires your expert assistance to complete.

I kindly request your help in providing the necessary data to fill in the remaining details for the cards. Your expertise in this matter would be truly invaluable.

I greatly appreciate your support and eagerly await your response. If there are any specific instructions or formatting requirements, please do let me know.

Thank you in advance for your time and assistance. I look forward to hearing from you soon.

**Comment by Anmol-Baranwal** [comment]
> Subject: Assistance Needed to Complete Blog Page
> 
> Hey @Anmol-Baranwal and @vinzvinci,
> 
> I hope this message finds you both well. I wanted to reach out and let you know that I have successfully added as much data as I could for the cards on the blog page. However, there is still some missing information that requires your expert assistance to complete.
> 
> I kindly request your help in providing the necessary data to fill in the remaining details for the cards. Your expertise in this matter would be truly invaluable.
> 
> I greatly appreciate your support and eagerly await your response. If there are any specific instructions or formatting requirements, please do let me know.
> 
> Thank you in advance for your time and assistance. I look forward to hearing from you soon.
> 
> Please refer to the provided screenshot for reference: image

I will get back to you after discussing it internally.

**Comment by mkubdev** [comment]
Hello, it's purely static. You did a great integration 👍🏻 
But you can stop here, the issue is fixed. Once the blog feature is developed, we'll use your cards!

**Comment by mkubdev** [comment]
Hey, at present, our website's blog is purely static and the development of the blog feature is still in progress.
Thank you a lot for your excellent work in integrating it - you've done an outstanding job since the start! 👍🏻 For the time being, you can cease your efforts on this task as the issue has been resolved. Rest assured, once the blog feature is fully developed, we will definitely incorporate your cards into the implementation. 🚀

**Comment by s2sharpit** [comment]
> Hey, at present, our website's blog is purely static and the development of the blog feature is still in progress. Thank you a lot for your excellent work in integrating it - you've done an outstanding job since the start! 👍🏻 For the time being, you can cease your efforts on this task as the issue has been resolved. Rest assured, once the blog feature is fully developed, we will definitely incorporate your cards into the implementation. 🚀

Thank you for the update! I'm glad to hear that the development of the blog feature is progressing. I appreciate your kind words about my integration work. It's been a pleasure working on this task, and I'm looking forward to seeing the final implementation. If there's anything else I can assist with in the meantime, please let me know. Thank you again!

**Comment by s2sharpit** [comment]
Hey @vinzvinci @mkubdev,

I truly appreciate your kind words about the work I've done on integrating the blog feature. Considering the blog feature's ongoing development, I'd like to request the merge of this pull request. We'll make the necessary adjustments when the blog feature is fully developed. Merging it now would be beneficial, as it could potentially save us from dealing with more complex merge conflicts later. Your support and understanding are valued. Let's move forward and get this merged! 🙌🏻🚀

**Review by vinzvinci — APPROVED** [review]
LGTM! We can update them soon!

**Comment by vinzvinci** [comment]
@Anmol-Baranwal the labels up to you and merge

**Comment by Anmol-Baranwal** [comment]
I am currently outside, I will merge this till 10 in th evening. 

> @Anmol-Baranwal the labels up to you and merge

**Comment by Anmol-Baranwal** [comment]
This could be level 2, but considering the complexity of the page and its responsiveness, I think the labels seem correct.

**Pull request merged**
