### PR TITLE
chore: link to Lumos Labs website

### PR DESCRIPTION
**Pull request by Panquesito7**
### Describe the changes you've made

- Link to Lumos Labs website.
  - All other partners are linked to their own websites, however, Lumos Labs was linked only to their Twitter. I believe we should link to their website directly so that they can find all of their socials and know about them easier. 🙂

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

I don't think this applies here.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Anmol-Baranwal — APPROVED** [review]
It ensures consistency, and all the social links are available in the `Stay updated with our journey` section.

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Comment by Anmol-Baranwal** [comment]
I have already reviewed the PR.

**Review by vinzvinci — COMMENTED** [review]
merging this now!

**Pull request merged**
