### PR TITLE
using src directory For Improving Code Organization

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue

Closes: #392 

### Describe the changes you've made

Incorporating the feature of Next.js 13, which allows for the addition of an "src" folder, could significantly improve the code organization within our project.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev @Mustafiz04 @Anmol-Baranwal  @Panquesito7 
I have created the pr again for pr #402 
Please check this PR.

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Review by thehashmap — APPROVED** [review]
LGTM!

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me

**Comment by s2sharpit** [comment]
Hey @vinzvinci 
I would request you to merge it ASAP, otherwise it will show merging conflicts like this pr #402 .

**Comment by vinzvinci** [comment]
All good!

**Pull request merged**
