### PR TITLE
using src directory

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue

Closes: #392 

### Describe the changes you've made

Incorporating the feature of Next.js 13, which allows for the addition of an "src" folder, could significantly improve the code organization within our project.

## Type of change
Improving Code Organization

What sort of change have you made:
using src directory to separate the application code from the project configuration files. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev
Please check this PR.

**Review by mkubdev — APPROVED** [review]
Hey :wave: LGTM!
This will be much clearer! 👍🏻

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Review by Anmol-Baranwal — APPROVED** [review]
It looks good to me, and I don't see any problems.

You changed `components` and `app` directories into a `src` directory within the project's folder structure, and it is visible from the paths.

I have a small suggestion: please avoid changing the styling of the code because it can make the review process more challenging when there are minor styling changes throughout the files. Perhaps consider disabling the default code formatting extension.

**Comment by s2sharpit** [comment]
> It looks good to me, and I don't see any problems.
> 
> You changed `components` and `app` directories into a `src` directory within the project's folder structure, and it is visible from the paths.
> 
> I have a small suggestion: please avoid changing the styling of the code because it can make the review process more challenging when there are minor styling changes throughout the files. Perhaps consider disabling the default code formatting extension.

Hey, I will take care of that in future.

**Comment by s2sharpit** [comment]
Hey @vinzvinci 
If everything is okay, please merge this PR.

**Comment by vinzvinci** [comment]
There are conflicting files in this, can't merge yet.  Can anyone fix? 
image

**Comment by s2sharpit** [comment]
Hey @vinzvinci 
I'm not able to resolve conflicts.
It shows me that you don't have write access.
image

**Comment by Anmol-Baranwal** [comment]
@s2sharpit 
You can resolve conflict using `command line` or `GitHub Desktop`

> Image
image

Or, you can directly compare the code from [your branch](https://github.com/WebXDAO/WebXDAO.github.io/compare/main...s2sharpit:WebXDAO.github.io:srcDirectory) to the code in the existing repository.

The description of the conflict already specifies the files that you need to check.

> Image
image

**Comment by Panquesito7** [comment]
Sometimes, it's best to create a new pull request as solving the merge conflicts (especially when there are folder changes and such) might take more time than making a new, fresh pull request.

**Comment by mkubdev** [comment]
@s2sharpit  You better should sync latest change from this PR in order to resolve merge conflicts!
Waiting for the resolution, let me know if you need help. :wave:

**Comment by vinzvinci** [comment]
Closing this PR. You can create new pr if u want!

**Pull request closed without merging**
