### PR TITLE
fix: `package.json` meta

### PR DESCRIPTION
**Pull request by Panquesito7**
### Describe the changes you've made

- Fix `package.json` meta.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

I don't think this applies here.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Anmol-Baranwal — COMMENTED** [review]
I am curious about the impact of this major change. What specific changes or impacts would it have?

**Comment by Panquesito7** [comment]
> I am curious about the impact of this major change. What specific changes or impacts would it have?

Not much, but it does not look professional to use a template name rather than the project name, as well as not providing an issue tracker link and repository link, IMO.
It does not harm if we provide those in the file. 🙂

**Comment by Anmol-Baranwal** [comment]
> > I am curious about the impact of this major change. What specific changes or impacts would it have?
> 
> Not much, but it does not look professional to use a template name rather than the project name, as well as not providing an issue tracker link and repository link, IMO. It does not harm if we provide those in the file. 🙂

Thanks for letting me know.

**Review by mkubdev — APPROVED** [review]
LGTM!

**Pull request merged**
