### PR TITLE
fix: remake project card with reg. to v3 design

### PR DESCRIPTION
**Pull request by vishnu9865**
#### Description of the bug
 - The projects card has different layout of information than the figma file.
 - The layout of the projects card with different width breakpoints change the projects card width.
 - Fix or update Read More button design.
 - Add box shadows based on v3 design.

Closes: #401 

### Describe the changes you've made
 - remade project card component with accordance to V3 Figma Design.
 - isolated project card component completely.
 - fixed full width of project card on small screens and mid-sized screens.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
The Change was tested visually using Chrome Responsive Mode.

## Checklist
- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented on my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| image | image |
| image | image |
| image | image |
| image | image |

## Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by vishnu9865** [comment]
@vinzvinci @shuklaritvik06 @darkterminal ,
Please feel free to ask for any changes to this PR.
Thank you in advance for taking your time.
Regards,
Jeyavishnu @vishnu9865

**Review by mkubdev — APPROVED** [review]
LGTM, thanks a lot for your contribution @vishnu9865 🤝

**Review by shuklaritvik06 — APPROVED** [review]
LGTM 🔥

**Review by vinzvinci — COMMENTED** [review]
Nice PR!

**Pull request merged**
