### PR TITLE
Update project page

### PR DESCRIPTION
**Pull request by Anuran12**
### Describe the changes you've made

 The current projects page's header does not match the blog and contributors page ui.. so i just remove the blue background 
image
image

##my change⬇️
image

I upgrade the repo cards

added fork counter and open issues. and added topic labels
image
image

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

tested by localhost

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| 
image
 | 
image
 |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/249"></a>

### CODE REVIEW

**Review by mkubdev — APPROVED** [review]
Hey @Anuran12 👋🏻 

Wow! This changes look awesome! 🔥 Everything look good to me! Keep this motivation 👍🏻

**Review by shuklaritvik06 — APPROVED** [review]
Looks good to me! Nice work @Anuran12 🎉

**Review by vinzvinci — APPROVED** [review]
LGTM!!!! Love it ❤️

**Comment by shuklaritvik06** [comment]
> LGTM!!!! Love it ❤️ 

Merging, thank you for your contribution :)

**Pull request merged**
