### PR TITLE
adding title to every page

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue

Closes: #418 

### Describe the changes you've made
Adding a title to every page and default title will be `WebXDAO`.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by s2sharpit** [comment]
Hey @Anmol-Baranwal @vinzvinci 
I would like to know your suggestion on the title of team page.
Is it should be `WebX Team - WebXDAO` or `Team - WebXDAO`.

For now, I have added title as `WebX Team - WebXDAO`.

Screenshot:
image

**Comment by vinzvinci** [comment]
Use `Team - WebXDAO`

**Comment by s2sharpit** [comment]
> Use `Team - WebXDAO`

I have updated as per your suggestion.

**Comment by s2sharpit** [comment]
Hey @Anmol-Baranwal 
Please review this PR.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me.

**Comment by s2sharpit** [comment]
Hey @mkubdev 
Please add appropriate labels to this PR 🙏.

**Pull request merged**
