### PR TITLE
docs: add dependabot workflow with proper conventions

### PR DESCRIPTION
**Pull request by Anmol-Baranwal**
## Related Issue

Closes: #507 

### Describe the changes you've made

```yml
version: 2
updates:
  # Update GitHub Actions
  - package-ecosystem: 'github-actions'
    labels:
      - 📦 dependencies
    directory: '/' # refers to the location of package.json
    commit-message:
      prefix: 'chore(deps)'
    schedule:
      interval: 'daily'
```

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

image

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mkubdev — APPROVED** [review]
LGTM 🙏

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Review by s2sharpit — APPROVED** [review]
LGTM!

**Comment by mkubdev** [comment]
The gh actions throw the following error (cc https://github.com/WebXDAO/WebXDAO.github.io/pull/526):
image

So i created the required label!

**Comment by vinzvinci** [comment]
> The gh actions throw the following error (cc #526): image
> 
> So i created the required label!

Thank you!

**Pull request merged**
