### PR TITLE
Update design of contributors page

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue

Closes: #446 

### Describe the changes you've made
Update contributors page

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| image | image |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mkubdev — APPROVED** [review]
Hello! Everything look good to me, thanks a lot for your contribution @s2sharpit 🙏

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
Please add another link for the commit history with the GitHub Icon in the lower part.

For example, the contributions of `mkubdev` can be found here: [Contributions of `mkubdev`](https://github.com/WebXDAO/WebXDAO.github.io/commits?author=mkubdev)

> You just need to use the username that is retrieved.

<hr>

See the steps:

1. Use the following URL: `https://api.github.com/repos/WebXDAO/WebXDAO.github.io/contributors` to retrieve the `login` value, which represents the username.

2. Then, construct the link using the format: `https://github.com/WebXDAO/WebXDAO.github.io/commits?author=<login_value>` to add the commit history link with the corresponding username.

**Comment by s2sharpit** [comment]
Thank you @Anmol-Baranwal for providing the instructions. I will add the commit history link with the GitHub Icon as requested. This will address the issue I was seeking assistance with, which is obtaining the link to the commit history.

Regarding the inclusion of Dependabot in the list, I understand your concern. I will exclude bots from the list to ensure it only displays human contributions.

**Comment by s2sharpit** [comment]
I have updated the PR.
Please review it @Anmol-Baranwal

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
> Image
image

I don't think that the icon showing commit history is best choice.

> Recommended icon
image

Yours is also appropriate, but it was confusing for me when I saw this for the first time. So, I believe that it will definitely be for others as well.

@s2sharpit 
What do you think?

**Comment by s2sharpit** [comment]
Hi @Anmol-Baranwal,

I wanted to let you know that I've implemented your suggestion for the icon displaying commit history, and I believe it looks much better now. Thank you for your valuable input!

image

**Review by Anmol-Baranwal — APPROVED** [review]
Thanks for the changes. 🚀 Looks good to me.

**Comment by s2sharpit** [comment]
Hey @vinzvinci @thehashmap @Anmol-Baranwal 
Please add appropriate labels to this PR 🙏.

**Comment by Anmol-Baranwal** [comment]
@thehashmap 
Please add the labels before merging the PR, because it may be neglected. Thanks for notifying us @s2sharpit

**Comment by thehashmap** [comment]
> @thehashmap Please add the labels before merging the PR, because it may be neglected. Thanks for notifying us @s2sharpit

Sure

**Pull request merged**
