### PR TITLE
feat: add email to redirect on clicking contact

### PR DESCRIPTION
**Pull request by a-s-t-e-y-a**
## Related Issue

- Information about the related issue

Closes: #449

### Describe the changes you've made

Uses mailto in href to copy the email and redirect the user to the default app for email 

## Type of change

Changes in the Footer.jsx

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mkubdev — APPROVED** [review]
Hey, look good to me! Thank you :)

**Review by Anmol-Baranwal — APPROVED** [review]
There is no code to copy it to the clipboard.

Still, I'm approving it as `@mkubdev` has approved this.

> There could be a problem, that if it gets copied then we would also have to implement toast to notify the user of the same.

This works and someone can of course copy the email from the link.

**Comment by a-s-t-e-y-a** [comment]
@Anmol-Baranwal okay so I have to add copy to clipboard feature also

**Comment by a-s-t-e-y-a** [comment]
@Anmol-Baranwal so when it will get merge

**Comment by Anmol-Baranwal** [comment]
I'm merging this!

PR Labeler gives a failed test, but I don't think it matters.

**Pull request merged**
