### PR TITLE
docs: minor grammatical error fix

### PR DESCRIPTION
**Pull request by virejdasani**
## Related Issue

- There was a grammatical mistake in the hero part of the website:
```
We are a opensource community...
```

Changed to:
```
We are an opensource community
```

### Describe the changes you've made
`a` changed to `an` to make it grammatically correct

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?
No tests need because of it being an extremely minor change

## Checklist
- [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented on my code, particularly wherever it was hard to understand.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ x] I have added tests that prove my fix is effective or that my feature works.
- [ x] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/213"></a>

### CODE REVIEW

**Review by krshkodes — APPROVED** [review]
Thank you for the contribution!

**Comment by Panquesito7** [comment]
Adding the `invalid` label as this is a very simple fix and shouldn't count for Hacktoberfest, IMO.
If you have any objections, let me know. Thank you for contributing. :)

**Comment by virejdasani** [comment]
Hey, @Panquesito7 I think this PR should count towards Hacktoberfest because even though it is a minor contribution, it does fix a grammatical error in the hero section of the page, an error, that can make WebX DAO look unprofessional.
Also, one of the core beliefs in the opensource community is that contributions of all sizes and types should be welcome, so if it isn't too much to ask, could you please remove the invalid label? It would help me out a lot, thanks!

**Comment by virejdasani** [comment]
@Panquesito7 @krshkodes any way you could remove the invalid tag please?

**Pull request merged**
