### PR TITLE
Gradient Heading

### PR DESCRIPTION
**Pull request by dhrumishah**
closing issue #329 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

image

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by darkterminal — COMMENTED** [review]
I have resolved the conflict and we need more reviews from other @WebXDAO/gssoc-mentors, @WebXDAO/webx-guild, and @WebXDAO/webx-guild-developer

**Review by vinzvinci — CHANGES_REQUESTED** [review]
Hi, we are expecting some errors because of this. Can you fix them or need some help?

image

**Review by darkterminal — APPROVED** [review]
@vinzvinci I have fixed the url values and made the read more button sparkling :sparkles:

**Review by vinzvinci — APPROVED** [review]
Awesome, thank you @darkterminal for helping! 

LGTM!

**Comment by darkterminal** [comment]
Woooo :hand: hi5!!! @dhrumishah :tada:

**Comment by dhrumishah** [comment]
> Woooo :hand: hi5!!! @dhrumishah :tada: 

Thank you 🤝🏼

**Pull request merged**
