### PR TITLE
Issue#389 Solved

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Related Issue

Resolved Navbar and Footer Responsiveness for devices having less than 400px width

Closes: #389 

### Describe the changes you've made
I used media queries to solve responsiveness of Navbar and Footer having width less than 400px. 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [x] This change requires a documentation update

## How Has This Been Tested?

Using the dev tools and checking for each and every devices. Adjusting width. 

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |
**Original**
image

**Updated**
Screenshot 2023-05-31 at 14 31 51

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mkubdev — COMMENTED** [review]
Hello @Vidip-Ghosh :wave:
Thanks a lot for your work and your contribution. Unfortunatly, i'm not seeing navbar issue since 67b03271a4143ca02c80fc3caca2f1086e5f2f81 fixed it!

You can test more here: https://webxdao.xyz/

Can you verify if you still facing this issue?

**Comment by Vidip-Ghosh** [comment]
> > > Hello @Vidip-Ghosh 👋 Thanks a lot for your work and your contribution. Unfortunatly, i'm not seeing navbar issue since [67b0327](https://github.com/WebXDAO/WebXDAO.github.io/commit/67b03271a4143ca02c80fc3caca2f1086e5f2f81) fixed it!
> > > You can test more here: https://webxdao.xyz/
> > > Can you verify if you still facing this issue?
> > 
> > 
> > Working fine for all devices and Navbar is alright in home page but I still found the following in Contributors Page: Screenshot 2023-05-31 at 18 22 17
> 
> Oh, well spotted for the contributors page. But it's isn't the navbar, it's due too `ContributorCard` which have padding in pixel.. 🙈

Even footer is also causing the issue.

**Comment by mkubdev** [comment]
> > > > Hello @Vidip-Ghosh 👋 Thanks a lot for your work and your contribution. Unfortunatly, i'm not seeing navbar issue since [67b0327](https://github.com/WebXDAO/WebXDAO.github.io/commit/67b03271a4143ca02c80fc3caca2f1086e5f2f81) fixed it!
> > > > You can test more here: https://webxdao.xyz/
> > > > Can you verify if you still facing this issue?
> > > 
> > > 
> > > Working fine for all devices and Navbar is alright in home page but I still found the following in Contributors Page: Screenshot 2023-05-31 at 18 22 17
> > 
> > 
> > Oh, well spotted for the contributors page. But it's isn't the navbar, it's due too `ContributorCard` which have padding in pixel.. 🙈
> 
> Even footer is also causing the issue. Actually, in dark mode I observed that some in footer some portion was in black instead of violet.

Mmm, that's strange.. Let's continue this together. 🤝
We just merged opened PR, this maybe caused the production code to have issues. In the last pr merged, the footer get some fix (Btw it cause a merge conflict on this PR, i can help you to fix it).
Can you merge main in this PR to see if the issue still persist ?

**Review by vinzvinci — COMMENTED** [review]
Thanks for contributions! Wait for the mentors and developers guild this coming weekdays.

**Comment by mkubdev** [comment]
@WebXDAO/gssoc-mentors Hi :wave: What is the state of this PR?

**Review by Anmol-Baranwal — CHANGES_REQUESTED** [review]
On testing the code in the local window, you can observe from the image that the structure of `footer.tsx` is incorrect.

> error
image

You can try fixing the error, which will result in the successful preview deployment on `Vercel`.

<hr>

I have fixed the error, but I don't see any noticeable difference.

After correcting the code, there is a gap in the navbar.

> Image1 
image

> Image2
image

While checking the same dimensions on the current official website of WebXDAO, there is no gap in the navbar:
> Image1
image

> Image2
image

@vinzvinci 
Please check again, as I don't believe this solution resolves the issue. Please correct me if I am mistaken. I have attached screenshots for reference.

> I have used chrome debugging for the same.

**Comment by vinzvinci** [comment]
any update on this?

**Comment by Vidip-Ghosh** [comment]
> any update on this?

It seems to be alright. You can close this PR

**Comment by vinzvinci** [comment]
> It seems to be alright. You can close this PR

Thanks! Will close this now 🚀

**Pull request closed without merging**
