### PR TITLE
New UI for community Partners Page and WebXDAO icon clickable

### PR DESCRIPTION
**Pull request by hackobansa**
## Related Issue

-  Updated the UI of Community Partners Page
- Update the UI for Community Partners Page 

### Describe the changes you've made

 I made update the background color of partners grid and I added Hover effect. and i made the WebXDAO clickable and it moves back to the homepage

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

 with #26 m run dev

## Checklist

- [ ] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

<a href="https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/199"></a>

### CODE REVIEW

**Comment by hackobansa** [comment]
this a proof of what i have done deployment soon
https://user-images.githubusercontent.com/56732809/193262567-52c03f72-45eb-4a1b-8da3-73a3c3dd13e5.mp4

**Review by krshkodes — CHANGES_REQUESTED** [review]
There are a lot of conflicts, can you please resolve them? Please tag us if you need any help

**Comment by hackobansa** [comment]
@krshkodes I need help deploying to github

**Comment by hackobansa** [comment]
I will fix it

**Comment by hackobansa** [comment]
> ## Related Issue
> * Updated the UI of Community Partners Page
> * Update the UI for Community Partners Page
> 
> ### Describe the changes you've made
> I made update the background color of partners grid and I added Hover effect. and i made the WebXDAO clickable and it moves back to the homepage
> 
> ## Type of change
> What sort of change have you made:
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [x]  Code style update (formatting, local variables)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  Documentation update.
> * [ ]  This change requires a documentation update
> 
> ## How Has This Been Tested?
> with #26 m run dev
> 
> ## Checklist
> * [ ]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [ ]  I have commented on my code, particularly wherever it was hard to understand.
> * [ ]  I have made corresponding changes to the documentation.
> * [ ]  My changes generate no new warnings.
> * [x]  I have added tests that prove my fix is effective or that my feature works.
> * [ ]  Any dependent changes have been merged and published in downstream modules.
> 
> ## Screenshots (if applicable)
> Original	Updated
> original screenshot	updated screenshot
> ## Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)
> 
> [](https://gitpod.io/#https://github.com/WebXDAO/WebXDAO.github.io/pull/199)

here's a link to the [Link to the repo](https://github.com/hackobansa/WebXDao.gitl)

**Pull request closed without merging**
