### PR TITLE
fixing invalid tailwind classname order

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Fixed the eslint error which was causing failure of build.

Closes: #352 

### Describe the changes you've made

I have fixed the formatting and used next/image where it was not used.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by s2sharpit** [comment]
Hey @vinzvinci @darkterminal @siddhi-244
I have fixed the issue #352 , please have a check

**Review by darkterminal — COMMENTED** [review]
It resembles the luminous glow of fireflies in the chilly darkness. ✨🌌

**Review by siddhi-244 — APPROVED** [review]

**Comment by s2sharpit** [comment]
Hey @siddhi-244 @darkterminal @vinzvinci 
I have a doubt that,
Is the pull request should also be assigned to be evaluated in leaderboard of GSSOC23?

**Review by Mustafiz04 — APPROVED** [review]

**Review by darkterminal — APPROVED** [review]

**Comment by Mustafiz04** [comment]
> Is the pull request should also assigned to be evaluated in the leaderboard of GSSOC23?

@s2sharpit I didn't get your question but any pull request that is successfully merged and has the gssoc'23 label will count for you in the leaderboard.

**Comment by vinzvinci** [comment]
and adding level will set you up. The higher the level, the more points you can get!

**Comment by s2sharpit** [comment]
> and adding level will set you up. The higher the level, the more points you can get!

But how can it be determined that a particular pull request should be attributed to a specific person or ID for evaluation purposes?

**Comment by s2sharpit** [comment]
> > > and adding level will set you up. The higher the level, the more points you can get!
> > 
> > But how can it be determined that a particular pull request should be attributed to a specific person or ID for evaluation purposes?
> > Does the PR should also be assigned for evaluation?
> 
> No they will determine by the number of merged pull requests and the number of issues you were assigned. So only assigning of issue enough not PR.
> You can see your dashboard by login into GSSoC website.

Hey, Thank you for your response @Mustafiz04

**Review by vinzvinci — APPROVED** [review]
Thank you!

**Pull request merged**
