### PR TITLE
Update Project Folder Name

### PR DESCRIPTION
**Pull request by Saurav-Pant**
.

issue: #287 

This pull request updates the project folder name from "projcts" to "projects" for consistency and clarity. The new folder name accurately reflects the contents and aligns with standard naming conventions. 
Closes: #287 

I have updated the project folder name from "projcts" to "projects" for consistency and clarity.

- [x] Bug fix (non-breaking change which fixes an issue)

I have tested the changes locally by verifying that the folder name is updated correctly and does not introduce any issues.

- - [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.
.

Original folder name: "projcts"
URL:- 
projects

Updated folder name: "Projects"

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct]

### CODE REVIEW

**Review by vinzvinci — COMMENTED** [review]
Thank you! Please wait for our mentors!

**Review by thehashmap — CHANGES_REQUESTED** [review]
Thanks for your contribution.
Please follow the PR [template](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/.github/PULL_REQUEST_TEMPLATE.md) mentioned in CONTRIBUTING.md

**Comment by darkterminal** [comment]
Please read this issue #286 about the PR and Merge 😄

**Comment by Saurav-Pant** [comment]
> Please read this issue #286 about the PR and Merge 😄

I contributed as mentioned in #286.

**Review by siddhi-244 — APPROVED** [review]

**Review by vinzvinci — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
