### PR TITLE
Modified Fonts according to prototype

### PR DESCRIPTION
**Pull request by praharshaAdhikari**
## Related Issue

-About integrating custom typographies from the prototype into the UI

Closes: # 278

### Describe the changes you've made

I changed the required fonts to Gilroy according to the prototype.
I also changed the color and style of "WEB" text according to the prototype.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

I checked by running the site locally.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by vinzvinci — CHANGES_REQUESTED** [review]
need more improvement in styling based on this issue https://github.com/WebXDAO/WebXDAO.github.io/issues/278
image

**Comment by Mustafiz04** [comment]
@praharshaAdhikari can you please make the change according to what @vinzvinci requested?

**Comment by vinzvinci** [comment]
it doesn't need to be look like it, but I think follow the color font there?

**Comment by mkubdev** [comment]
I regret to inform you that we have made the decision to close this pull request. After careful consideration, we believe that the issue mentioned in #278 is not suitable for contributions from external contributors at this time. We apologize for any inconvenience caused and sincerely appreciate the effort and contribution you have made. Your input has been invaluable to our project. Thank you for your understanding and continued support. 🙏

Please feel free to reach out if you have any further questions or would like to contribute in other areas of our project. We value your participation and hope to collaborate with you in the future.

Best regards,

**Pull request closed without merging**
