### PR TITLE
refactoring landing page code

### PR DESCRIPTION
**Pull request by s2sharpit**
## Related Issue

- Information about the related issue

  Code for the home page is quite extensive and complex, making it difficult to locate specific sections or make modifications efficiently.

Closes: #353 

### Describe the changes you've made

Refactoring the code by dividing the home page into smaller, more manageable section components

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev 
Please have a look to this PR.

**Comment by s2sharpit** [comment]
Hey @shuklaritvik06 @vinzvinci @mkubdev @darkterminal @siddhi-244 
Please review this PR.

**Review by mkubdev — APPROVED** [review]
Hello again @s2sharpit ! That look perfect to me! Thanks a lot for your work. ⚡🚀

**Comment by s2sharpit** [comment]
Hey @shuklaritvik06 @vinzvinci @mkubdev @darkterminal @siddhi-244
I found that this pr has conflicts that must be resolved but I'm not able to resolve it.
It shows me that I don't have write access.

image

**Comment by s2sharpit** [comment]
> > Hey @shuklaritvik06 @vinzvinci @mkubdev @darkterminal @siddhi-244 I found that this pr has conflicts that must be resolved but I'm not able to resolve it. It shows me that I don't have write access.
> > image
> 
> Hello 👋 Yes, it was my fault sorry for that! I fixed conflicts and merged your PR :) Thanks a lot @s2sharpit ! See you on our discord ==> https://discord.gg/4epKhYrd

Hey, धन्यवाद for merging this PR.

**Review by vinzvinci — COMMENTED** [review]
Nice collab and contributions! Putting gssoc label to this.

**Pull request merged**
